In [21]:
#Q1

import numpy as np
array = np.array([(1,2),(3,4)])
print("array", array)
list = array.tolist()

print("list", list)


array [[1 2]
 [3 4]]
list [[1, 2], [3, 4]]


In [12]:
#Q2
import numpy as np

array = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(array)
trace = np.trace(array)
print("trace",trace)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
trace 15


In [18]:
#Q3
import numpy as np
array = np.array([[2, 1, 9],
                [3, 5, 1]])

print(array[array>2])

[9 3 5]


In [20]:
#Q4
import numpy as np
arr1 = np.array([(1,2,3)])
arr2 = np.array([(4,5,6)])

adding = arr1 + arr2
print(adding)

[[5 7 9]]
